import React from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { FiDownload, FiFileText, FiUser, FiActivity } from 'react-icons/fi';
import './PDFReport.css';

const PDFReport = ({ result, chartsRef, patientName, patientId, patientAge, doctorNotes }) => {
  const generatePDF = async (detailed = false) => {
    if (!result) {
      alert('No analysis results available for PDF generation.');
      return;
    }

    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const { class: label, confidence } = result;

      // Layout coordinates helper
      let currentY = 15;

      // 1. Header Section
      pdf.setFillColor(5, 8, 14); // dark theme color
      pdf.rect(0, 0, 210, 40, 'F');

      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(22);
      pdf.setTextColor(16, 185, 129); // emerald accent
      pdf.text('NEURODIAGNOSTICS CLINICAL REPORT', 20, 20);

      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10);
      pdf.setTextColor(148, 163, 184); // slate text
      pdf.text('Automated Brain Tumor MRI Classification & Diagnostic Report', 20, 28);
      pdf.text(`Generated by: Anand (anand.settu2006@gmail.com)`, 20, 34);

      currentY = 50;

      // 2. Patient & Observer Metadata Grid
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(13);
      pdf.setTextColor(18, 24, 38);
      pdf.text('1. Patient & Observation Data', 20, currentY);
      pdf.line(20, currentY + 2, 190, currentY + 2);
      
      currentY += 10;
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10);
      pdf.setTextColor(71, 85, 105);

      // Print patient details
      pdf.text(`Patient Full Name:  ${patientName || 'Anonymous Patient'}`, 20, currentY);
      pdf.text(`Medical Record ID:  ${patientId || 'MR-N/A'}`, 110, currentY);
      currentY += 7;
      pdf.text(`Patient Age:             ${patientAge || 'N/A'}`, 20, currentY);
      pdf.text(`Imaging Modality:    MRI (T1-Weighted Contrast)`, 110, currentY);
      
      currentY += 7;
      pdf.text(`Report Date:            ${new Date().toLocaleDateString()}`, 20, currentY);
      pdf.text(`Analysis Time:         ${new Date().toLocaleTimeString()}`, 110, currentY);
      
      currentY += 10;

      // 3. Diagnostic Results Block
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(13);
      pdf.setTextColor(18, 24, 38);
      pdf.text('2. AI Diagnostic Outcome', 20, currentY);
      pdf.line(20, currentY + 2, 190, currentY + 2);

      currentY += 10;
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(12);
      pdf.setTextColor(239, 68, 68); // warning red
      pdf.text(`Classification Outcome:  ${label} Presence Detected`, 20, currentY);
      
      pdf.setTextColor(18, 24, 38);
      pdf.text(`Confidence Rating:        ${confidence}% Probability`, 20, currentY + 7);

      currentY += 17;

      // 4. Clinical notes / description
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(13);
      pdf.text('3. Pathological Observations & Guidelines', 20, currentY);
      pdf.line(20, currentY + 2, 190, currentY + 2);

      currentY += 10;
      
      const getTumorDescription = (tumorType) => {
        switch (tumorType) {
          case 'Glioma': return 'Gliomas represent primary brain tumors originating in glial cells. The AI scan identifies structural abnormalities conforming to glioma density grids. Clinical observation recommends checking for micro-lesion margins and surrounding tissue edema.';
          case 'Meningioma': return 'Meningiomas arise from the meningeal membranes. Typically slow-growing, they generate mass-effects against brain hemispheres. Surgical margins should be investigated based on visual contrast borders.';
          case 'No Tumor': return 'Normal anatomical scan. No evidence of masses, midline shifts, or contrast enhancements indicating tumor cells. Periodic monitoring is advised if symptoms persist.';
          case 'Pituitary': return 'Pituitary adenomas arise in the sella turcica region. Proximity to the optic chiasm requires immediate visual field mappings. Hormonal panel tests are indicated.';
          default: return 'Atypical pathological margins identified. Correlation with MRI spectroscopy is advised.';
        }
      };

      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10);
      pdf.setTextColor(71, 85, 105);
      const description = getTumorDescription(label);
      const descLines = pdf.splitTextToSize(description, 170);
      pdf.text(descLines, 20, currentY);

      currentY += (descLines.length * 5) + 5;

      // Custom doctor notes
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(10);
      pdf.setTextColor(18, 24, 38);
      pdf.text('Clinical Observer Notes:', 20, currentY);
      
      pdf.setFont('helvetica', 'italic');
      pdf.setFontSize(9.5);
      pdf.setTextColor(100, 116, 139);
      const notes = doctorNotes || "No additional clinician annotations entered in report file.";
      const noteLines = pdf.splitTextToSize(notes, 170);
      pdf.text(noteLines, 20, currentY + 5);

      currentY += (noteLines.length * 5) + 12;

      // 5. Verification charts (if detailed & ref exists)
      if (detailed && chartsRef && chartsRef.current) {
        // Add a page break for the charts page
        pdf.addPage();
        currentY = 15;
        
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(14);
        pdf.setTextColor(18, 24, 38);
        pdf.text('4. Diagnostic Data Visualizations', 20, currentY);
        pdf.line(20, currentY + 2, 190, currentY + 2);
        
        currentY += 10;

        const canvas = await html2canvas(chartsRef.current, {
          scale: 2,
          backgroundColor: '#0a111a'
        });
        const imgData = canvas.toDataURL('image/png');
        const imgWidth = 170;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;
        
        pdf.addImage(imgData, 'PNG', 20, currentY, imgWidth, imgHeight);
        currentY += imgHeight + 15;
      }

      // 6. Sign-off / footer section
      if (currentY > 240) {
        pdf.addPage();
        currentY = 20;
      } else {
        currentY = 240;
      }

      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.setTextColor(148, 163, 184);
      pdf.line(20, currentY, 190, currentY);
      
      currentY += 6;
      pdf.text('Diagnostic verification conducted by NEURODIAGNOSTICS Clinical Engine.', 20, currentY);
      pdf.text('Anand • Lead AI Developer • anand.settu2006@gmail.com', 20, currentY + 4);
      
      pdf.setFont('helvetica', 'bold');
      pdf.text('APPROVED SIGNATURE:', 120, currentY);
      pdf.line(120, currentY + 12, 180, currentY + 12);
      
      // Save PDF
      const docName = `neuro_diagnosis_${patientId || 'scan'}_${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(docName);

    } catch (err) {
      console.error("Error creating report PDF:", err);
      alert("Failed to build PDF report. Please check the browser console for details.");
    }
  };

  return (
    <div className="pdf-report-container animate-fade-in">
      <div className="pdf-report-header">
        <h3>
          <FiFileText style={{ color: 'var(--accent-cyan)' }} />
          Clinical Report Export Deck
        </h3>
        <p>Export authenticated clinical outcomes in PDF format.</p>
      </div>

      <div className="pdf-report-buttons">
        <button 
          type="button"
          className="pdf-btn basic-report"
          onClick={() => generatePDF(false)}
          disabled={!result}
        >
          <FiDownload />
          Clinical Report
        </button>
        
        {chartsRef && chartsRef.current && (
          <button 
            type="button"
            className="pdf-btn detailed-report"
            onClick={() => generatePDF(true)}
            disabled={!result}
          >
            <FiDownload />
            Visual Analytics Report
          </button>
        )}
      </div>

      <div className="pdf-report-info">
        <div className="info-card">
          <h4>
            <FiUser style={{ color: 'var(--accent-cyan)' }} />
            Clinical Report
          </h4>
          <ul>
            <li>Patient clinical parameters</li>
            <li>AI outcomes & confidence ratings</li>
            <li>Pathological descriptions</li>
            <li>Sign-off endorsement margins</li>
          </ul>
        </div>

        <div className="info-card">
          <h4>
            <FiActivity style={{ color: 'var(--accent-purple)' }} />
            Analytics Report
          </h4>
          <ul>
            <li>All basic clinical metadata</li>
            <li>Rendered probability charts</li>
            <li>Multi-class distribution details</li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default PDFReport;